# Generated by Django 5.2.3 on 2025-06-30 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                (
                    "codigo_iso2",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="Código ISO 2"
                    ),
                ),
                (
                    "codigo_iso3",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Código ISO 3"
                    ),
                ),
                (
                    "ddi",
                    models.CharField(
                        help_text="Ex: +55 para Brasil",
                        max_length=5,
                        verbose_name="Código DDI",
                    ),
                ),
                (
                    "codigo_siscomex",
                    models.CharField(
                        max_length=5, unique=True, verbose_name="Código Siscomex"
                    ),
                ),
                ("continente", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "País",
                "verbose_name_plural": "Países",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "sigla",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="Sigla UF"
                    ),
                ),
                (
                    "codigo_ibge",
                    models.CharField(
                        blank=True,
                        help_text="Código oficial do estado",
                        max_length=2,
                        null=True,
                        verbose_name="Código IBGE",
                    ),
                ),
                (
                    "regiao",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Sudeste, Nordeste, etc.",
                        max_length=50,
                        null=True,
                        verbose_name="Região",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estados",
                        to="dashboard.pais",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
                "ordering": ["nome"],
                "unique_together": {("nome", "pais")},
            },
        ),
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "codigo_ibge",
                    models.CharField(
                        blank=True,
                        help_text="Código oficial da cidade, se aplicável",
                        max_length=10,
                        null=True,
                        verbose_name="Código IBGE",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True,
                        help_text="Faixa de CEP (se houver)",
                        max_length=9,
                        null=True,
                        verbose_name="CEP Inicial",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cidades",
                        to="dashboard.estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cidade",
                "verbose_name_plural": "Cidades",
                "ordering": ["nome"],
                "unique_together": {("nome", "estado")},
            },
        ),
    ]
