# Generated by Django 5.2.3 on 2025-07-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_objetivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficioINSS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("codigo", models.CharField(max_length=20, unique=True)),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Benefício INSS",
                "verbose_name_plural": "Benefícios INSS",
                "ordering": ["nome"],
            },
        ),
    ]
