# Generated by Django 5.2 on 2025-07-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_beneficioinss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficioinss',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='beneficioinss',
            name='valor',
        ),
    ]
