# Generated by Django 5.2 on 2025-07-11 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_beneficioinss_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(default='', max_length=60, verbose_name='Nome')),
                ('insituacao', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nrcpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('nrrg', models.CharField(blank=True, max_length=10, null=True, verbose_name='Registro Geral')),
                ('nrhabilitacao', models.CharField(blank=True, max_length=15, null=True, verbose_name='Habilitação')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('telefone_comercial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=250, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data ult. alteração')),
                ('nacionalidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nacionalidade')),
                ('naturalidade', models.CharField(blank=True, max_length=60, null=True, verbose_name='Naturalidade')),
                ('nome_mae', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome da mãe')),
                ('nome_pai', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome do pai')),
                ('profissao', models.CharField(blank=True, max_length=60, null=True, verbose_name='Profissão')),
                ('idcidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cidade', verbose_name='Cidade')),
                ('idestadocivil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.estadocivil', verbose_name='Estado Civíl')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
                'unique_together': {('nrcpf',)},
            },
        ),
    ]
